Добавила кнопку "add" и сделала список
Pelga/Function pull request #3
Opened 2023-09-22 10:25 UTC by Pelga

Добавила кнопку "add" и сделала список

2023-09-22 10:31 UTC, Wainow commented
Переименуй 
Добавила кнопку "add" и сделала список -> Feature/TASK-1: Добавила кнопку "add" и сделала список

2023-09-22 10:33 UTC, Wainow commented
Пройдись по всем файлам которые ты изменила
_править файл по код стайлу:_
`option + command + L`
_править импорты:_
`control + option + O`

2023-09-22 10:43 UTC, Pelga commented
> Переименуй
> Добавила кнопку "add" и сделала список -> Feature/TASK-1: Добавила кнопку "add" и сделала список

Переименовала

2023-09-22 10:54 UTC, Pelga commented
> Пройдись по всем файлам которые ты изменила
> _править файл по код стайлу:_
> `option + command + L`
> _править импорты:_
> `control + option + O`

Сделала правки

2023-09-22 10:58 UTC, Wainow requested changes

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
>          RecyclerView recycler_view2;
переменные в java записываются в стиле camelCase
в твоем случае
recycler_view2 -> recyclerView2

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
>          RecyclerView recycler_view2;
и все остальные переменные поправь тоже

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +    TabAdapter tabAdapter;
тебе нужно внимательно просмотреть все переменные и проверить их область видимости
например если переменная используется только внутри класса то она `private`
они могут быть `public private package-private protected`
тоже самое относится и к методам

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +        tabAdapter = new TabAdapter(list);
подсвечивает 
<img width="808" alt="Screenshot 2023-09-22 at 16 40 44" src="https://github.com/Pelga/Function/assets/62390803/012dca94-0e92-4424-af16-613b82188118">

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +                .setTitle("Function point")
Хорошим тоном считается выносить строки в отдельную статическую переменную
например так
public static final String DIALOG_TITLE = "Function point"
в этом случае константы не пишутся в стиле camelCase а просто с заглавных букв и _ вместо пробелов

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +                .setTitle("Function point")
посмотри по коду и мб где то еще есть такие же строчки

2023-09-22 10:58 UTC, Wainow commented on app/src/main/res/layout/new_activity.xml
> +        android:backgroundTint="#575555"
в андроид ресурсах тоже можно выносить в константы типо `@color/black`
тут тоже не приветствуется хранить открыто ресурсы

2023-09-22 10:58 UTC, Wainow commented on app/src/main/res/layout/new_activity.xml
> +        android:backgroundTint="#575555"
посмотри где еще такое же встречается и замени

2023-09-22 10:58 UTC, Wainow commented on app/src/main/res/layout/tabulated_function.xml
> +        android:textSize="50dp" />
50dp в константу

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +                          if (!x_dialog2.getText().toString().trim().equals("") || y_dialog2.getText().toString().equals("")) {
вот здесь очень много раз вызывается` x_dialog2.getText().toString()`
в программировании лучше делать минимум повторений и не копировать один и тот же вызов
лучше вынести это в отдельную переменную и в местах вызова использовать эту переменную

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +        public void applyText(FunctionPoint functionPoint);
<img width="554" alt="Screenshot 2023-09-22 at 16 51 29" src="https://github.com/Pelga/Function/assets/62390803/0b779c0b-8c3f-49fd-aaad-489d7a090cea">

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +        View view = inflater.inflate(R.layout.dialog, null);
<img width="892" alt="Screenshot 2023-09-22 at 16 52 51" src="https://github.com/Pelga/Function/assets/62390803/eeb6ccfe-7b90-4628-a1b6-941a14dc1b2e">

2023-09-22 10:58 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/TabAdapter.java
> +    class TabViewHolder extends RecyclerView.ViewHolder {
<img width="455" alt="Screenshot 2023-09-22 at 16 54 45" src="https://github.com/Pelga/Function/assets/62390803/156a862b-82a0-4bba-b451-71513ca0cd22">

2023-09-22 15:33 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
>          RecyclerView recycler_view2;
Исправила

2023-09-22 15:33 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +    TabAdapter tabAdapter;
Исправила

2023-09-22 15:33 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +        tabAdapter = new TabAdapter(list);
Исправила

2023-09-22 15:33 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +                .setTitle("Function point")
Исправила

2023-09-22 15:33 UTC, Pelga commented on app/src/main/res/layout/new_activity.xml
> +        android:backgroundTint="#575555"
Исправила

2023-09-22 15:33 UTC, Pelga commented on app/src/main/res/layout/tabulated_function.xml
> +        android:textSize="50dp" />
Исправила

2023-09-22 15:33 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +                          if (!x_dialog2.getText().toString().trim().equals("") || y_dialog2.getText().toString().equals("")) {
Исправила

2023-09-22 15:33 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +        public void applyText(FunctionPoint functionPoint);
Исправила

2023-09-22 15:34 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +        View view = inflater.inflate(R.layout.dialog, null);
Исправила

2023-09-22 15:34 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/TabAdapter.java
> +    class TabViewHolder extends RecyclerView.ViewHolder {
Исправила

2023-09-23 04:37 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +    TabAdapter tabAdapter;
нет, я вижу что остались, посмотри еще внимательнее

2023-09-23 04:39 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +                .setTitle("Function point")
нужно в отдельный класс со всеми public static, назвать его Constants

2023-09-23 04:40 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +                          if (!x_dialog2.getText().toString().trim().equals("") || y_dialog2.getText().toString().equals("")) {
мб ты не запушила, я чет не вижу у себя изменений в этом

2023-09-23 04:46 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +        RecyclerView recyclerView2;
нет смысла объявлять переменную и инициализировать в разных тут
тут это можно сделать в одной строчке
`RecyclerView recyclerView2 = findViewById(R.id.recycler_view2);`

2023-09-23 04:47 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +        FloatingActionButton add_button;
нет смысла объявлять переменную и инициализировать в разных местах
тут это можно сделать в одной строчке
`FloatingActionButton add_button = findViewById(R.id.add_button);`

**+ тут название должно быть в _camelCase_**

2023-09-23 04:48 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
>          Intent intent = getIntent();
если у тебя переменная используется только в 1 месте, то не вижу смысла сохранять ее в отдельное поле
то есть можно сразу записать
`ArrayTabulatedFunction list = (ArrayTabulatedFunction) getIntent().getSerializableExtra(ARRAY);`

2023-09-23 04:50 UTC, Wainow commented on app/src/main/java/com/example/myapplication/MainActivity.java
> +        EditText left_domain_border = findViewById(R.id.right_domain_border);
тут все переменные остались в старых названиях
переменные в джава записываются в **_camelCase_**

2023-09-23 04:51 UTC, Wainow commented on app/src/main/java/com/example/myapplication/MainActivity.java
> +        MaterialButton material_button;
нет необходимости делать инициализацию и обьявление переменной в разных местах
если все это можно записать одной строчкой
`MaterialButton material_button = findViewById(R.id.material_button);`

2023-09-23 04:53 UTC, Wainow commented on app/src/main/java/com/example/myapplication/MainActivity.java
> +    private String toStr(EditText editText) {
в классе newActivity нужен такой же метод
но чтобы не делать копипасту (дубляж) метода
нужен отдельный класс в котором этот метод будет статический
и оба класса будут использовать этот метод
_ну или любой другой способ, где этот метод будет лежать в одном месте_

2023-09-25 05:33 UTC, Pelga commented
> Переименуй
> Добавила кнопку "add" и сделала список -> Feature/TASK-1: Добавила кнопку "add" и сделала список

Переименовала

2023-09-25 05:42 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +    TabAdapter tabAdapter;
> нет, я вижу что остались, посмотри еще внимательнее

исправила

2023-09-25 05:53 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +                .setTitle("Function point")
> Constants

Исправила

2023-09-25 05:55 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +        RecyclerView recyclerView2;
Исправила

2023-09-25 05:57 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +        FloatingActionButton add_button;
Исправила

2023-09-25 05:58 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
>          Intent intent = getIntent();
Исправила

2023-09-25 06:02 UTC, Pelga commented on app/src/main/java/com/example/myapplication/MainActivity.java
> +        EditText left_domain_border = findViewById(R.id.right_domain_border);
Исправила

2023-09-25 06:02 UTC, Pelga commented on app/src/main/java/com/example/myapplication/MainActivity.java
> +        MaterialButton material_button;
Исправила

2023-09-25 06:13 UTC, Pelga commented on app/src/main/java/com/example/myapplication/MainActivity.java
> +    private String toStr(EditText editText) {
Исправила

2023-09-25 08:05 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +
лишний пробел

2023-09-25 08:05 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Constants.java
> +    public static final String NULL_1 = "";
у тебя две одинаковые константы. У них одно и тоже значение. тебе достаточно одной из них

2023-09-25 08:05 UTC, Wainow commented on app/src/main/java/com/example/myapplication/MainActivity.java
> +
лишний пробел

2023-09-25 08:05 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Constants.java
> +    public static final String ARRAY_1 = "array";
тоже самое. Вообще бессмысленно заводить константы с одним и тем же значением

2023-09-25 08:05 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +
лишний пробел

2023-09-25 08:13 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/NewActivity.java
> +
Исправила

2023-09-25 08:13 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Constants.java
> +    public static final String NULL_1 = "";
Исправила

2023-09-25 08:13 UTC, Pelga commented on app/src/main/java/com/example/myapplication/MainActivity.java
> +
Исправила

2023-09-25 08:13 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Constants.java
> +    public static final String ARRAY_1 = "array";
Исправила

2023-09-25 08:14 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyDialogFragment.java
> +
Исправила

2023-09-25 09:13 UTC, Wainow approved these changes

2023-09-26 07:26 UTC, Pelga commented
task-1

2023-09-26 07:26 UTC, merged