Feature/TASK-5: Библиотека Room
Pelga/Function pull request #7
Opened 2023-11-09 07:50 UTC by Pelga

2023-11-09 07:59 UTC, Wainow commented
не так называется задача, каждый раз одно и тоже

2023-11-13 12:41 UTC, Wainow requested changes
ты не прошлась линтером (command option L + command option O)

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/TabAdapter.java
> +import java.util.List;
лишний импорт

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/TabAdapter.java
> +    MyDao dao = database.myDao();
неиспользуемая переменаая

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/TabAdapter.java
> +    MyDatabase database = App.getInstance().getDatabase();
когда создаешь переменные надо думать какая у них область видимости и ставить соответствующее ключевое слово

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyFragment.java
> +    public List<FunctionPoint> toList(ArrayTabulatedFunction list) {
неиспользуемый метод

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyFragment.java
> +                for (int i = 0; i < tabAdapter.getList().size(); i++){
`tabAdapter.getList()` много раз вызываешь. Я вроде писал что лучше всегда минимум повторений

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/App.java
> +        database = Room.databaseBuilder(this, MyDatabase.class, "database").allowMainThreadQueries().build();
константа

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/App.java
> +    public static App instance;
почему public

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDao.java
> +    int deleteById(double id);
не используется

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDao.java
> +    MyEntity getById(double id);
не используется

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyDatabase.java
> +
тут не нужен пробел

2023-11-13 12:41 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyFragment.java
> +import static com.example.myapplication.Constants.ARRAY;
тут много имортов не используется

2023-11-14 05:41 UTC, Pelga commented
> ты не прошлась линтером (command option L + command option O)

Сделала

2023-11-14 05:42 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/TabAdapter.java
> +import java.util.List;
Убрала

2023-11-14 05:42 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/TabAdapter.java
> +    MyDao dao = database.myDao();
Убрала

2023-11-14 05:44 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/TabAdapter.java
> +    MyDatabase database = App.getInstance().getDatabase();
Поправила

2023-11-14 05:45 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyFragment.java
> +    public List<FunctionPoint> toList(ArrayTabulatedFunction list) {
Убрала

2023-11-14 05:46 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyFragment.java
> +                for (int i = 0; i < tabAdapter.getList().size(); i++){
Сделать отдельной переменной?

2023-11-14 05:47 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/App.java
> +    public static App instance;
Поменяла

2023-11-14 05:47 UTC, Wainow commented on app/src/main/java/com/example/myapplication/Laba6/MyFragment.java
> +                for (int i = 0; i < tabAdapter.getList().size(); i++){
да. Не стоит вызывать геттер несколько раз в одном методе, если его можно сохранить в локальную переменную

2023-11-14 05:47 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyDao.java
> +    int deleteById(double id);
Убрала

2023-11-14 05:48 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyDao.java
> +    MyEntity getById(double id);
Убрала

2023-11-14 05:48 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyDatabase.java
> +
Убрала

2023-11-14 05:49 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyFragment.java
> +import static com.example.myapplication.Constants.ARRAY;
убрала

2023-11-14 05:54 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/MyFragment.java
> +                for (int i = 0; i < tabAdapter.getList().size(); i++){
Поменяла

2023-11-14 05:56 UTC, Pelga commented
Проверяй

2023-11-14 05:59 UTC, Wainow commented
еще есть вопросы без ответов

2023-11-14 06:02 UTC, Wainow commented
<img width="828" alt="Screenshot 2023-11-14 at 12 01 56" src="https://github.com/Pelga/Function/assets/62390803/81269f20-13d3-41f5-ab59-24a165234366">

2023-11-14 06:02 UTC, Wainow commented
<img width="817" alt="Screenshot 2023-11-14 at 12 02 18" src="https://github.com/Pelga/Function/assets/62390803/4a23f466-8e54-41f7-96a8-0ffbf46677bd">

2023-11-14 06:42 UTC, Pelga commented
> <img alt="Screenshot 2023-11-14 at 12 01 56" width="828" src="https://user-images.githubusercontent.com/62390803/282677632-81269f20-13d3-41f5-ab59-24a165234366.png">

что это??

2023-11-14 06:44 UTC, Wainow commented
> > <img alt="Screenshot 2023-11-14 at 12 01 56" width="828" src="https://user-images.githubusercontent.com/62390803/282677632-81269f20-13d3-41f5-ab59-24a165234366.png">
> 
> что это??

если много комментариев он закрывает некоторые вопросы. Нужно нажать Load more

2023-11-14 06:45 UTC, Pelga commented on app/src/main/java/com/example/myapplication/Laba6/App.java
> +        database = Room.databaseBuilder(this, MyDatabase.class, "database").allowMainThreadQueries().build();
Убрала

2023-11-14 06:49 UTC, Pelga commented
@Wainow

2023-11-14 06:50 UTC, Wainow approved these changes

2023-11-14 06:52 UTC, merged